# Generated by Django 6.0.3 on 2026-04-29 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricehistory",
            options={
                "ordering": ["-checked_at"],
                "verbose_name_plural": "PriceHistories",
            },
        ),
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("dark", "Тёмная"), ("light", "Светлая")],
                        default="dark",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "English")],
                        default="ru",
                        max_length=2,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "Рубль"), ("USD", "Доллар"), ("EUR", "Евро")],
                        default="RUB",
                        max_length=3,
                    ),
                ),
                (
                    "check_interval",
                    models.PositiveSmallIntegerField(
                        default=24, help_text="Частота проверки (часы)"
                    ),
                ),
                ("email_notifications", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
