# Generated by Django 6.0.3 on 2026-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_pricehistory_options_usersetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="normalized_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=500,
                verbose_name="Нормализованное название",
            ),
        ),
    ]
