# Generated by Django 6.0.3 on 2026-05-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_normalized_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="delivery_days",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Срок доставки"
            ),
        ),
    ]
