# Generated by Django 6.0.3 on 2026-05-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_offer_delivery_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersetting",
            name="language",
        ),
        migrations.AlterField(
            model_name="usersetting",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "Рубль"),
                    ("USD", "Доллар"),
                    ("EUR", "Евро"),
                    ("KZT ", "Тенге"),
                ],
                default="RUB",
                max_length=4,
            ),
        ),
    ]
