# Generated by Django 6.0.3 on 2026-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_usersetting_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersetting",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "Рубль"),
                    ("USD", "Доллар"),
                    ("EUR", "Евро"),
                    ("KZT", "Тенге"),
                ],
                default="RUB",
                max_length=4,
            ),
        ),
    ]
