# Generated by Django 6.0.3 on 2026-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_usersetting_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="title",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Название предложения",
            ),
        ),
    ]
