# Generated by Django 6.0.3 on 2026-05-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_offer_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="target_price",
        ),
        migrations.AddField(
            model_name="usersetting",
            name="price_change_threshold",
            field=models.PositiveSmallIntegerField(
                default=10, help_text="При каком изменении цены уведомлять (%)"
            ),
        ),
    ]
