# Generated by Django 6.0.3 on 2026-05-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_subscription_target_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersetting",
            name="last_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда последний раз обновлялись данные о товарах",
                null=True,
            ),
        ),
    ]
