# Generated by Django 6.0.3 on 2026-05-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_usersetting_last_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_notified_delivery_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Срок доставки при прошлом уведомление",
            ),
        ),
    ]
